### ISSUE TITLE
Allow non-string JSON parameter values

### ISSUE THREAD

**Issue by 1ec5** [nerdishbynature/RequestKit#10]
`Router` expects all the parameter values to be `String`s, but if the payload for a request can be JSON-encoded, it should be possible for a parameter value to be another JSON-representable type, such as a number or array of strings. Specifically, I was unable to implement support for setting labels or milestones on issues in nerdishbynature/octokit.swift#36 because the API expects an array of strings for labels and a numeric ID for the milestone.

**Comment by pietbrauer** [comment]
Fixed with #15
