### ISSUE TITLE
Swift3 Adaptations

### ISSUE THREAD

**Issue by tiferrei** [nerdishbynature/RequestKit#19]
Small problem on the `String+Additions` file for `swift3`:

`let characterSet = CharacterSet.urlQueryAllowed.mutableCopy() as! NSMutableCharacterSet` –> Value of type 'CharacterSet' has no member 'mutableCopy'.

Can be related to this:
[SE-0069](https://github.com/apple/swift-evolution/blob/master/proposals/0069-swift-mutability-for-foundation.md)

**Comment by phatblat** [comment]
I've been working on migrating this to the new Swift 3 API over in phatblat/RequestKit@fd5ec7fa742470dcadf303379187ae4123784a8c. While it compiles, there's a crash during testing.

```
21:41:31.210 xctest[51028:1841098] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply received
21:41:33.093 xctest[51028:1841109] _IDE_startExecutingTestPlanWithProtocolVersion:21
Test Suite 'All tests' started at 2016-06-18 21:41:33.139
Test Suite 'RequestKitTests.xctest' started at 2016-06-18 21:41:33.141
Test Suite 'ConfigurationTests' started at 2016-06-18 21:41:33.142
Test Case '-[RequestKitTests.ConfigurationTests testCustomImplementation]' started.
Test Case '-[RequestKitTests.ConfigurationTests testCustomImplementation]' passed (0.007 seconds).
Test Case '-[RequestKitTests.ConfigurationTests testDefaultImplementation]' started.
Test Case '-[RequestKitTests.ConfigurationTests testDefaultImplementation]' passed (0.001 seconds).
Test Suite 'ConfigurationTests' passed at 2016-06-18 21:41:33.154.
Executed 2 tests, with 0 failures (0 unexpected) in 0.008 (0.012) seconds
Test Suite 'RouterTests' started at 2016-06-18 21:41:33.155
Test Case '-[RequestKitTests.RouterTests testRequest]' started.
-[Foundation._SwiftNSCharacterSet mutableCopyWithZone:]: unrecognized selector sent to instance 0x7ff38174aa80
(null)

140683824435112

objc[51028]: pthread_rwlock_rdlock failed (11)
(lldb)
```

I'm guessing these Foundation mutability changes aren't quite done in Xcode 8 beta 1.

**Comment by phatblat** [comment]
Filed [rdar://26880260](http://openradar.appspot.com/26880260).

Found that using `NSCharacterSet.urlQueryAllowed()` instead of `CharacterSet.urlQueryAllowed` avoids this crash.

@pietbrauer Do you want to start a `swift-3.0` branch on the main repo? If you can create it I can send up a PR with my changes.

**Comment by tiferrei** [comment]
Yup @phatblat had the exact same thing, thanks for the tip!

**Comment by tiferrei** [comment]
@phatblat BTW, can't this be related to [SE-0069](https://github.com/apple/swift-evolution/blob/master/proposals/0069-swift-mutability-for-foundation.md)?

**Comment by pietbrauer** [comment]
@phatblat @tiferrei I made #21 for the Swift 3.0 changes, for me the tests run through.

**Comment by tiferrei** [comment]
@pietbrauer from my side, Xcode 8 Beta:
- Swift 2.3 compiling ✅
- Swift 2.3 tests ✅
- Swift 3 compiling ✅
- Swift 3 tests ✅

All good!

**Comment by tiferrei** [comment]
Is master going to be `swift3`?
