### ISSUE TITLE
One framework with multiple APIs

### ISSUE THREAD

**Issue by ghost** [nerdishbynature/RequestKit#24]
Good morning, sorry to bother but I would like to know if it possible to use RequestKit with multiple APIs. I would like to create a single framework that would "speak" to multiple APIs, for example, creating a "Social framework" which is able to handle connections with the Facebook API, Twitter API, etc. But in one, unified framework.

Thank you,
MrAppleMan

**Comment by pietbrauer** [comment]
I did not have such use cases in mind when I created this framework. It might be possible but I don't think it would be very elegant.
