### ISSUE TITLE
Swift 3.0 Xcode Beta 6

### ISSUE THREAD

**Issue by tiferrei** [nerdishbynature/RequestKit#25]
Good evening, 
I believe the swift 3 branch needs to be updated for the beta 6, it comes up with some nasty bugs when I try to use the new beta.

Thank you,
tiferrei

**Comment by pietbrauer** [comment]
Fixed in #21

**Comment by tiferrei** [comment]
The last commit for #21 was in 22 of June?

**Comment by pietbrauer** [comment]
I rebased today with Xcode GM, trust me.

**Comment by tiferrei** [comment]
Thank you!
