### ISSUE TITLE
Xcode 8.1 requires Swift version 3.0.1

### ISSUE THREAD

**Issue by tiferrei** [nerdishbynature/RequestKit#27]
Good evening, 

I keep getting an error whilst developing for [TanukiKit](https://www.github.com/nerdishbynature/TanukiKit), as Xcode requires me to update dependent frameworks to Swift 3.0.1, the error is as follows:

```
Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1
```

Thank you,
tiferrei

**Comment by pietbrauer** [comment]
There is no release with Xcode 8.1 yet. You can use `carthage bootstrap --no-use-binaries` for now.
