### ISSUE TITLE
Router crashing on TanukiKit Unit Tests

### ISSUE THREAD

**Issue by tiferrei** [nerdishbynature/RequestKit#35]
Hello there,

first of all, I apologise if this issue is not 100% caused by RequestKit, I was not completely sure wether to open it here or in TanukiKit, but here made more sense as the crash happens with RequestKit.

When running a simple [unit test](https://github.com/tiferrei/TanukiKit/blob/commits/TanukiKitTests/CommitTests.swift#L11) to get the commits from a project, I am presented with a crash on [this line](https://github.com/nerdishbynature/RequestKit/blob/master/RequestKit/Router.swift#L53):
```
#0	0x00000001112348c5 in Router.request() -> URLRequest? at /Users/tiferrei/Developer/TanukiKit/Carthage/Checkouts/RequestKit/RequestKit/Router.swift:53
RequestKit was compiled with optimization - stepping may behave oddly; variables may not be available.
```
As you can see, the logs don't really say anything specific, what I know is that the project compiles successfully, but crashes on the test, furthermore, all other tests pass, only this one crashes.
If it helps, I pushed a commit to Travis to get [some logs](https://travis-ci.org/nerdishbynature/TanukiKit/builds/194119405).

If there's any further debugging I can do from my side, please request it, I only provided this information because I didn't how to further debug it.

Tiago

**Comment by pietbrauer** [comment]
Unfortunately the "backtrace" is not saying anything. Can you say which block of code is causing this crash?

**Comment by tiferrei** [comment]
@pietbrauer do you mean the code from TanukiKit causing the crash or the line in RequestKit that is running when the thread exits?

**Comment by pietbrauer** [comment]
The TanukiKit code, would be nice if I can reproduce it

**Comment by tiferrei** [comment]
Oh yeah absolutely, it's the HEAD of the commits branch on my fork: https://github.com/tiferrei/TanukiKit/tree/70bdc11d45cf341f1739d88bfceec95ef98183cf
And the crash happens on: https://github.com/tiferrei/TanukiKit/blob/commits/TanukiKitTests/CommitTests.swift#L11

**Comment by pietbrauer** [comment]
In your router you are doing:

```swift
var path: String {
        switch self {
        case .readCommits(let id):
            return "project/\(id)/repository/commits"
...
```

which leads to `id` being a configuration (first argument in the enum) this can be fixed by writing:

```swift
var path: String {
        switch self {
        case .readCommits(_, let id, _, _, _):
            return "project/\(id)/repository/commits"
...
```

**Comment by tiferrei** [comment]
Ah of course! Sorry about that. Just for future reference, should this kind of issues be opened in RequestKit or TanukiKit?

**Comment by pietbrauer** [comment]
Should be discussed in your PR. The force unwrap is there on purpose to spot errors during developments.
