### ISSUE TITLE
Parsing variable array attributes

### ISSUE THREAD

**Issue by tiferrei** [nerdishbynature/RequestKit#36]
Good morning,
I am trying to come up with a way to represent this with an object:
```json
{
    "timetable":{
        "2018-01-29": [
            {
                "location": {
                    "address": [
                        "29 Gordon Sq",
                        "London",
                        "WC1H 0PP"
                    ],
                    "name": "Gordon House 106",
                    "sitename": "Gordon House",
                    "type": "CB",
                    "capacity": 50
                },
                "end_time": "18:00:00",
                "module": {
                    "module_id": "COMP3058",
                    "lecturer": {
                        "email": "ucacdgo@ucl.ac.uk",
                        "name": "GORSE, Denise (Dr)"
                    },
                    "name": "Artificial Intelligence and Neural Computing",
                    "course_owner": "COMPS_ENG",
                },
                "duration": 120,
                "start_time": "16:00:00"
            }
        ]
    },
    "ok": true
}
```
The part that is troubling me is the `"2018-01-29"` array, which shows the date for an appointment. I'm not seeing how I can set the value of the variable to its JSON if the attribute changes with the data. So for example I can't just do:
```swift
date = json["any YYY-MM-DD date in here?"] as ...
```

Do you know of any way to handle this or is there something in the JSON or REST standards that says that atributtes should be static and predictable? Making an API change might be an option, but only if this turns out to be a violation of the protocols.

Thank you,
Tiago

**Comment by pietbrauer** [comment]
This seems very wrong to me. It should be an array of appointments and then one appointment has a date as a property. Keys should be pre-defined by the API and not changing, the “key” illustrated here is basically a value.
