### ISSUE TITLE
Update CocoaPods podspec so the current version is 2.1.0 instead of 2.0.2

### ISSUE THREAD

**Issue by mpvosseller** [nerdishbynature/RequestKit#40]
CocoaPods currently shows the latest version as 2.0.2 when it should be 2.1.0
https://cocoapods.org/pods/NBNRequestKit
https://github.com/nerdishbynature/RequestKit/blob/master/NBNRequestKit.podspec
https://github.com/CocoaPods/Specs/blob/master/Specs/b/b/8/NBNRequestKit/2.0.2/NBNRequestKit.podspec.json

**Comment by pietbrauer** [comment]
Oops, sorry. Could you make a Pull Request?

**Comment by mpvosseller** [comment]
@pietbrauer I'm unfamiliar with the process of managing a CocoaPod but it looks like the last thing we need to do is to add the latest `NBNRequestKit.podspec` to the CocoaPods Specs repo as  `Specs/b/b/8/NBNRequestKit/2.1.0/NBNRequestKit.podspec.json`

Is that right? Is that something I can do or do you need to do that?

**Comment by pietbrauer** [comment]
I had to do it. 2.1.0 is now the most recent version.

**Comment by mpvosseller** [comment]
Thank you @pietbrauer
