### ISSUE TITLE
Allow API user to specify the type in RequestKitErrorResponseKey

### ISSUE THREAD

**Issue by mpvosseller** [nerdishbynature/RequestKit#48]
@pietbrauer  @tiferrei

Related to https://github.com/nerdishbynature/RequestKit/issues/38 and https://github.com/nerdishbynature/RequestKit/pull/39 

Right now if a request is not successful the returned JSON is parsed as a generic `[String: AnyObject]` and placed into `userInfo[RequestKitErrorResponseKey]`. How would you feel about allowing the developer to specify the specific type to parse that JSON as?

By way of example, a developer might define a structure like this:
```
struct MyErrorResponse : Codable {
    var message : String?
    var field : String?
    var code : Int?
}
```

And then they could pass `expectedErrorResponseType:MyErrorResponse.self` to `load` like this:
```
    func getJSON(_ session: RequestKitURLSession = URLSession.shared, completion: @escaping (_ response: Response<[String: AnyObject]>) -> Void) -> URLSessionDataTaskProtocol? {
        let router = JSONTestRouter.testGET(configuration)
        return router.load(session, expectedResultType: [String: AnyObject].self, expectedErrorResponseType:MyErrorResponse.self) { json, error in
            if let error = error {
                completion(Response.failure(error))
            } else {
                if let json = json {
                    completion(Response.success(json))
                }
            }
        }
    }
```

If a request was not successful and `expectedErrorResponseType` was provided then RequestKit would parse the JSON with that specific type.

The user could then more easily access the value out of `userInfo[RequestKitErrorResponseKey]` like this:

```
        let task = TestInterface().getJSON(session) { response in
            switch response {
            case .success:
                print("success")
            case .failure(let error as NSError):
                let myError = error.userInfo[RequestKitErrorKey] as? MyErrorResponse
                print(myError.message)
                print(myError.field)
                print(myError.code)
            }
        }
```

We might even consider just passing the `MyErrorResponse` object as the error itself but I haven't thought that all through.

WDYT?

**Comment by tiferrei** [comment]
@mpvosseller I love this, I wanted to eventually implement this but I thought it was too big of a jump for 2.2.0. I think now’s a good time.

**Comment by mpvosseller** [comment]
@tiferrei assuming @pietbrauer is on board I probably wouldn't get to this for a while so feel free to take it on.

**Comment by tiferrei** [comment]
@mpvosseller thanks, I would, but unfortunately, exam's season is coming soon so I don't think I'd have a lot of time for it.

**Comment by pietbrauer** [comment]
I am also pretty packed with work right now but I see the value and am open for suggestions on how to implement this.

**Comment by mpvosseller** [comment]
Ok, great! I'll try to implement this when I have the time.

**Comment by pietbrauer** [comment]
Closing since there hasn't been an update in a while.
