### ISSUE TITLE
Support for adding custom http header

### ISSUE THREAD

**Issue by BernardTolosajr** [nerdishbynature/RequestKit#49]
Hi, Is there a support for adding a custom headers?  

Thank you.

**Comment by BernardTolosajr** [comment]
Here is my branch with custom HTTP headers, but im not sure if this is the right path. 

https://github.com/BernardTolosajr/RequestKit/commit/81180a7b1c1935d950d9e9c371ec382581c59544

Thank you

**Comment by pietbrauer** [comment]
Hey Bernard, this looks good to me. Do you mind opening a PR?

**Comment by BernardTolosajr** [comment]
@pietbrauer sure ill open a PR.

**Comment by tiferrei** [comment]
Closing as the PR has been merged.
