### ISSUE TITLE
The documentation on CocoaPods website is out of date

### ISSUE THREAD

**Issue by mpvosseller** [nerdishbynature/RequestKit#50]
The documentation on the CocoaPods website is out of date:
https://cocoapods.org/pods/NBNRequestKit

Observe the uppercase enums like`case .GetMyself` instead of `case .getMyself` among many other changes as compared to the most recent `README.md` on github.

Also (related?) the Documentation link (on the right side bar) points at http://cocoadocs.org/docsets/NBNRequestKit/2.2.0 which gives a 404.

**Comment by pietbrauer** [comment]
I'm afraid CocoaDocs doesn't exist anymore. From the [README](https://github.com/CocoaPods/cocoadocs.org). For the RequestKit README I have no idea why it doesn't get updated.

> CocoaDocs was deprecated back in early 2015 and now has a replacement for the CocoaPods-specific infrastructure. If you've come to get help about a CocoaDocs page, I'm afraid it doesn't exist anymore.
