### ISSUE TITLE
This library makes using URLSession.dataTask ambiguous

### ISSUE THREAD

**Issue by mxcl** [nerdishbynature/RequestKit#62]
The additional `dataTask` function this library declares makes normal use of `URLSession` ambiguous, is this desired? It's quite inconvenient for consumers.

**Comment by pietbrauer** [comment]
This library has an interface on URLSessionDataTask, dataTasks are returned as usual but can be switched out to provide better testability or for mocking the network request.

**Comment by mxcl** [comment]
Yes, but it makes any use of URLSession.dataTask ambiguous in any file I need to import this library or a dependent and disambiguating them is tricky, it took me a few tries to make Swift happy. As long as you’re aware.
