### ISSUE TITLE
Breaking API Changes

### ISSUE THREAD

**Issue by pkandrashkou** [nerdishbynature/RequestKit#76]
Hello @pietbrauer. I think it would have been better to release changes from `2.5.0` as a major version bump as of now it breaks some projects such as https://github.com/nerdishbynature/octokit.swift and https://github.com/danger/swift. 

I could not find any issues related to this yet, but I can see that the release is still quite fresh, so I assume this is not only my local issue.

I think the main reason is the deletion of the `Response` structure [here](https://github.com/nerdishbynature/RequestKit/pull/75/files#diff-fd1f744e6d6361b564033fe24980d6b9fae7938e5e054ebb3afe196c12fd26aeL6). However, I am not 100% sure this is the only breaking change because I have not investigated it further and as far as I can see there are quite a lot of changes apart from that one.

Nevertheless, I think another part of the story is that these projects use `RequestKit` as a dependency with `package(name:url:from:)` and the [Apple Documentation](https://developer.apple.com/documentation/swift_packages/package/dependency/3582850-package) states:
> Adds a package dependency that uses the version requirement, starting with the given minimum version, going up to the next major version.

Personally, I think it would be better to revert and re-release the `RequestKit` to save the trouble for other developers changing their `Package.swift` files to pin the `2.3.0` release or updating their the usage code to the new API which is more time-consuming tbh 🙂

Please let me know if more information is required from my side. I would be glad to help.

_Originally posted by @pkondrashkov in https://github.com/nerdishbynature/RequestKit/issues/75#issuecomment-1001485967_

**Comment by pietbrauer** [comment]
I revoked the 2.5.0 release and will re-release as 3.0.0. Sorry for the trouble.
