### ISSUE TITLE
Should 2.5.0 be 3.0?

### ISSUE THREAD

**Issue by diederich** [nerdishbynature/RequestKit#77]
Hey Piet! 👋 

I saw the `RequestKit` 2.5.0 tag appear via an SPM update. It looks like `OctoKit` fails to build with it, given the `Response` public type is gone from the interface.

Could maybe make the 2.5.0 a 3.0 instead, which would prevent the upgrade in `OctoKit` (and other things depending on `Response`) ?

Thank you! Happy holidays! :-)

**Comment by pietbrauer** [comment]
Hey Stephan,

yes, this was a mishap on my end.

I rereleased 2.5.0 as 3.0.0: https://github.com/nerdishbynature/RequestKit/releases/tag/3.0.0

Happy holidays to you too!! ☃️

**Comment by diederich** [comment]
Thank you! 🙏
